### ISSUE TITLE
Dépendance serial-number 🤔

### ISSUE THREAD

**Issue by cestef** [Malakrovi/sponsorbot#1]
Mais que fait cette dep ici 🤔🤔🤔

**Comment by Malathub** [comment]
Je n'ai pas eu le temps de clean le package.json, mon script de base est dépendant d'une clé d'authentification car de base il est payant.

**Comment by Malathub** [comment]
c'est bon, c maintenant retiré

**Comment by papycochon** [comment]
> c'est bon, c maintenant retiré

c'est* boss
